// generated by stringer -type=ReduceFeedbackType; DO NOT EDIT

package strategy

import "fmt"

const _ReduceFeedbackType_name = "UnknownGoodBad"

var _ReduceFeedbackType_index = [...]uint8{7, 11, 14}

func (i ReduceFeedbackType) String() string {
	if i < 0 || i >= ReduceFeedbackType(len(_ReduceFeedbackType_index)) {
		return fmt.Sprintf("ReduceFeedbackType(%d)", i)
	}
	hi := _ReduceFeedbackType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ReduceFeedbackType_index[i-1]
	}
	return _ReduceFeedbackType_name[lo:hi]
}
