.PHONY: all clean coverage debug-install dependencies fmt generate install lint markdown test testverbose tools

export ARGS := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
export PKG := github.com/zimmski/tavor
export ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

all: dependencies install test

clean:
	go clean -i ./...
	go clean -i -race ./...
coverage:
	go test -coverprofile=coverage.out
	go tool cover -html=coverage.out
crosscompile:
	gox -os="linux" ./...
debug-install: clean
	go install -race -v ./...
dependencies:
	go get -t -v ./...
	go build -v ./...
fmt:
	gofmt -l -w $(ROOT_DIR)/
generate:
	go generate ./...
install:
	go install -v ./...
lint: install fmt
	$(ROOT_DIR)/scripts/lint.sh
markdown:
	orange
test:
	go test -race ./...
testverbose:
	go test -race -v ./...
tools:
	# generation
	go get -u -v golang.org/x/tools/cmd/stringer

	# linting
	go get -u -v golang.org/x/lint/golint/...
	go get -u -v github.com/kisielk/errcheck/...

	# code coverage
	go get -u -v golang.org/x/tools/cmd/cover
	go get -u -v github.com/onsi/ginkgo/ginkgo/...
	go get -u -v github.com/modocache/gover/...
	go get -u -v github.com/mattn/goveralls/...
