// generated by stringer -type=ParserErrorType; DO NOT EDIT

package token

import "fmt"

const _ParserErrorType_name = "ParseErrorNoStartParseErrorNewLineNeededParseErrorEarlyNewLineParseErrorEmptyExpressionIsInvalidParseErrorEmptyStringParseErrorEmptyTokenDefinitionParseErrorInvalidArgumentValueParseErrorInvalidTokenNameParseErrorInvalidTokenTypeParseErrorUnusedTokenParseErrorMissingTypedTokenArgumentParseErrorNonTerminatedStringParseErrorNoTokenForVariableParseErrorRepeatWithOptionalTermParseErrorTokenAlreadyDefinedParseErrorTokenNotDefinedParseErrorTypeNotDefinedForTypedTokenParseErrorExpectRuneParseErrorExpectOperatorParseErrorUnknownBooleanOperatorParseErrorUnknownConditionParseErrorUnknownTypedTokenArgumentParseErrorUnknownTypedTokenTypeParseErrorUnknownTokenAttributeParseErrorUnexpectedTokenDefinitionTerminationParseErrorExpectedExpressionTermParseErrorEndlessLoopDetectedParseErrorExpectedEOFParseErrorRootIsNilParseErrorUnexpectedEOFParseErrorUnexpectedData"

var _ParserErrorType_index = [...]uint16{0, 17, 40, 62, 96, 117, 147, 177, 203, 229, 250, 285, 314, 342, 374, 403, 428, 465, 485, 509, 541, 567, 602, 633, 664, 710, 742, 771, 792, 811, 834, 858}

func (i ParserErrorType) String() string {
	if i < 0 || i+1 >= ParserErrorType(len(_ParserErrorType_index)) {
		return fmt.Sprintf("ParserErrorType(%d)", i)
	}
	return _ParserErrorType_name[_ParserErrorType_index[i]:_ParserErrorType_index[i+1]]
}
